### ISSUE TITLE
Turns Red/Green but nothing happens

### ISSUE THREAD

**Issue by svanderbleek** [sculpt0r/vim-browser-extension#6]
I smashed my option keys on MacOS Chrome and eventually the red dot turned green but then nothing changes, the text input acts the same as before.

**Comment by sculpt0r** [comment]
Thanks for the report. I will mark this one as closed since it seems to duplicate https://github.com/sculpt0r/vim-browser-extension/issues/5.

Please follow #5 for the further updates.
